apiVersion: apps/v1
kind: Deployment
metadata:
  name: "${NAME}"
spec:
  replicas: ${BATCH}
  selector:
    matchLabels:
      app: "${NAME}"
  template:
    metadata:
      labels:
        app: "${NAME}"
    spec:
      containers:
      - image: public.ecr.aws/jg/curlit:latest
        name: "${NAME}"
        resources:
          requests:
            cpu: "${CPU}"
            memory: "${MEM}"
      automountServiceAccountToken: false
      tolerations:
      - key: karpenter
        operator: Exists
      nodeSelector:
        kubernetes.io/arch: amd64
        karpenter.sh/capacity-type: on-demand
      topologySpreadConstraints:
      - maxSkew: 5
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
      - maxSkew: 5
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: DoNotSchedule

