---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curlit-gpu
  labels:
    app: curlit-gpu
spec:
  replicas: ${BATCH}
  selector:
    matchLabels:
      app: curlit-gpu
  template:
    metadata:
      labels:
        app: curlit-gpu
    spec:
      containers:
      - name: hello
        imagePullPolicy: Always
        image: public.ecr.aws/jg/curlit
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "${MEM}"
            cpu: "${CPU}"
          limits:
            memory: "${MEM}"
            cpu: "${CPU}"
          limits:
            nvidia.com/gpu: "1"
      nodeSelector:
        kubernetes.io/arch: amd64
